name: tunisie_libertaire
description: "Application officielle du blog Tunisie Libertaire"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# Désactiver toutes les plateformes sauf Android
platforms:
  android:
  # ios: (désactivé)
  # linux: (désactivé)
  # macos: (désactivé)
  # web: (désactivé)
  # windows: (désactivé)